### ISSUE TITLE
Synbeta srcds_run issue

### ISSUE THREAD

**Issue by Quesoteric** [Balimbanana/SourceScripts#5]
Tried to install the synergy beta with the [syndsinstall.sh](https://github.com/Balimbanana/SourceScripts/blob/master/unix/syndsinstall.sh) script. Can confirm I am using latest version of the script.
The issue in question:
```
RB
./syndsinstall.sh: ./steamapps/common/synbeta/srcds_run: /bin/sh^M: bad interpreter: No such file or directory
Thu Apr 18 02:34:29 UTC 2024 WARNING: SynDS closed or crashed, restarting.
Thu Apr 18 02:34:30 UTC 2024 SynDS started.
./syndsinstall.sh: ./steamapps/common/synbeta/srcds_run: /bin/sh^M: bad interpreter: No such file or directory
Thu Apr 18 02:34:30 UTC 2024 WARNING: SynDS closed or crashed, restarting.
Thu Apr 18 02:34:31 UTC 2024 SynDS started.
./syndsinstall.sh: ./steamapps/common/synbeta/srcds_run: /bin/sh^M: bad interpreter: No such file or directory
Thu Apr 18 02:34:31 UTC 2024 WARNING: SynDS closed or crashed, restarting.
```
As you can see, trying to run the server causes this to flood the console. The server OS is an Ubuntu 22.04 linux machine.

**Comment by Balimbanana** [comment]
This is an issue that occurs when an executable is either modified or created on Windows, then copied over without testing.
As far as I know, the development beta is not really functional on Linux, but you can try it if you wish.

The fix for any program that gives `/bin/sh^M` that I generally use is in `vi`:
```
vi ./srcds_run
:%s/<Ctrl+V then Enter>//
:wq
```
When you do Ctrl+V and press Enter, it should show up as: `^M` if it worked correctly. Just putting in `:%s/^M//` will not work, as it is seen as 2 characters instead of the dos newline single character which looks the same.
There are some programs that allow replacement of those characters from the command line, but they require additional installs, so I haven't included any automatic fixes for it.

**Comment by Quesoteric** [comment]
Oh, it's not good with linux to begin with? Whoops
